import sys
import os
import glob


def copy_tests(result_dir, target_project_path, target_dir):
    '''
    Copy test cases of given project to target path for running.
    :param result_dir: path to test case directory generated by ChatGPT.
    :param target_project_path: path to target project
    :param target_dir: path to target directory used to store test cases
    '''
    # os.chdir(result_dir)
    tests = glob.glob(result_dir + "/**/*Test.java", recursive=True)
    # target_project = target_project_path.rstrip('/').split('/')[-2:] # for module composed project, e.g., gson
    target_project = os.path.basename(target_project_path.rstrip('/'))
    print("Copying tests to ", target_project, '...')

    for tc in tests:
        # tc should be 'pathto/project/testcase'.
        tc_project = tc.split('/')[-4].split('%')[1]
        if tc_project != target_project or \
                not os.path.exists(target_project_path):
            continue

        target = target_dir

        _ = [os.makedirs(os.path.join(target, dir_name), exist_ok=True) for dir_name in
             ("test_cases", "compiler_output", "test_output", "report")]

        # print(f"Copying [{tc}] [{os.path.join(target, 'test_cases')}]")
        os.system(f"cp {tc} {os.path.join(target, 'test_cases')}")


if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python copy_tests.py <test_case_results_path> <target_project_path> <tests_dir>")
        sys.exit()
    copy_tests(*sys.argv[1:])
